

try {

    console.log("#####")

    //throw "MY ERROR"

}catch(e){
    console.log(e);
}

finally{
    console.log("sono nel blocco finally")
}

console.log("Sono fuori dal blocco try ")
console.log("Proseguo")


